# This sets the default config for each job to use full VMs.
# The VMs have 2 cores and 8 GB of RAM
dist: trusty
sudo: required
services:
  - mysql
language: python
python:
  - "3.6"
cache: pip

before_install:
  - sh script/installation/before_install.sh

install:
  - sh script/installation/install.sh

script:
  - source activate eva
  - pycodestyle  --select E src/ test/ --exclude src/filters,src/parser/evaql
  - PYTHONPATH=./ pytest test/ --cov-report= --cov-config=.coveragerc --cov=src/ -s -v --log-level=10

after_success:
  - coveralls
